### ISSUE TITLE
Add strings for Donor #1

### ISSUE THREAD

**Issue by ramigeraisy** [ramigeraisy/food-basket-delivery#1]
Use the Translate function (that is used today to switch family to soldier) and add "donor" option:

כיום קיימת אפשרות לשנות את המונח משפחות לחיילים – שווה לעקוב אחרי הקוד של איך זה עובד ולהוסיף עוד אפשרות של תורמים.
התרגום עצמו נעשה באמצעות בפונקציה translate.ts שמשתמשים בה גם בקבצי TYPESCRIPT וגם בקבצי HTML:
את ההגדרה עצמה מגדירים בהגדרות מערכת בשדה הנקרא :
forSoldiers
שים לב שהגדרות המערכת נטענות לפני שהמערכת עולה – בהתאם לקוד בapp.module.ts בשורה 210 .

**Comment by morfi11** [comment]
I believe this is already ion production. To keep this board in shape - @ramigeraisy please link the PR to the issue and mark it as done.

**Comment by ramigeraisy** [comment]
https://github.com/noam-honig/food-basket-delivery/pull/412
