### ISSUE TITLE
לאפשר למתנדב לבטל שיוך מסויים

### ISSUE THREAD

**Issue by morfi11** [ramigeraisy/food-basket-delivery#28]
השיוך נעשה ללא תקשורת ישירה עם המתנדב וצריך לאפשר לו לסרב משלוח

רצוי שמתנדב יוכל גם לאשר קבלת משימה

כלומר כפתורים למשלוח בכרטיס מתנדב: 
1. קיבלתי ואבצע
2. לא יכול לבצע - נמא להעביר למישהו אחר
3. אספתי
4. היתה בעייה

**Comment by noam-honig** [comment]
נשמע לי כמו סטטוס משלוח, לא נמסר אחר - לא מעוניין

**Comment by morfi11** [comment]
לא מספיק טוב להן כי זה לא נותן סינון לפי סטטוס. הרעיון לעשות שיוך לפי העדפות המערכת ואז לקבל תגובה מהמתנדב שקיבל סמס. 
צריך סטטוס חדש למשלוח - "נדחה" - ואז הוא ימשיך להופיע ב"לא משוייכים" או אולי ב"נדחו ע"י המתנדב".
יש הבדל בין משלוח שלא שוייך (ואז אפשר פשוט לשייך אותו) לבין כזה שנדחה ואז צריך לשייך ולשים לב שלא חוזרים למי שסירב.
