### ISSUE TITLE
Add Lab as last point on route

### ISSUE THREAD

**Issue by ramigeraisy** [ramigeraisy/food-basket-delivery#3]
b. להוסיף אפשרות בהגדרות מערכת –
i. להגדיר שסיום המסלול הוא נקודת החלוקה – (גם עבור איסוף וגם עבור חלוקה שרוצים מסלול מעגלי)
ii. להציג את כתובת נקודת החלוקה כסיום המסלול בUI של המתנדב – יוצג במסלול של המתנדב.

הערות לפיתוח:

הUI של המתנדב הוא נקרא my-families.component.ts
חישוב המסלול נעשה ב asign-family.component.ts בServer Function שנקרא RefreshRoute. עיקר העבודה נעשה ב optimizeRoute בכמה שלבים:
a. מציאת נקודת התחלה (כיום לפי הרשימת חלוקה) שורה 732
b. סידור המשפחות לפי הקרובות ביותר לקודמת – 735-767
c. פנייה לגוגל לחישוב המסלול - שורה 768
i. שים לב – גוגל צריך נקודת התחלה ונקודת סיום – כרגע נקודת ההתחלה היא מיקום רשימת החלוקה – ונקודת הסיום היא הנקודה האחרונה לפי החישוב בסעיף B .
d. שמירת סדר המשלוחים ברשומת המשלוח (1,2 וכו...)בשורות 769-815

**Comment by noam-honig** [comment]
https://github.com/noam-honig/food-basket-delivery/issues/457
https://github.com/noam-honig/food-basket-delivery/issues/459
