### ISSUE TITLE
להוסיף התייחסות לכמות הציוד שנתרם ונאסף. באתר התורמים מזינים כמויות של "מחשב", "מחשב נייד" או "מסך". נכון להיום המידע נשמר בחגי כטקטס הערה משורשר ולא כשדות שניתנים לסיכום, מיון וסינון.

### ISSUE THREAD

**Issue by morfi11** [ramigeraisy/food-basket-delivery#35]
מציע להשתמש בשדות של "סוג סל" ו"כמות" ולייצר משלוח לכל סוג. 
יש לוודא שמשלוחים מאותו תורם ישוייכו תמיד ביחד לאותו מתנדב - כלומר לייצר קישור בין משלוחים.

**Comment by noam-honig** [comment]
סה"כ הכמות נשמרת בשדה כמות - כך שזה נותן איזה שהיא אינדיקציה.
אופציה אחרת - היא לפצל את שורת התרומה בהתאמה ולהתייחס לזה כסוג סל (מחשב, נייד, מסך) וכמות.

**Comment by morfi11** [comment]
אני חושב שאופציה 2 עדיפה - לפצל את התרומות לסוגי סלים שונים.
אבל זה יחייב בהמשך לחבר משלוחים בזמן שיוך באופן אוטומטי.
אולי כדאי להוסיף מזהה "משלוח על" שיאגד מספר משלוחים

**Comment by noam-honig** [comment]
המשלוח על הוא התורם.
כאשר השיוך נעשה מתוך שיוך מתנדבים - זה מציע אוטומטית את האחרים.
אתה רוצה להוסיף אפשרות כזו גם לכפתור שיוך  מתוך מעקב משלוחים?
(הכי מצחיק זה שהדבר הבא שתבקשו זה להחזיר את הסיכום משלוח כדי שיוכלו לראות כמה סה"כ מחשבים/מסכים/ניידים הוא צריך לאסוף)

**Comment by morfi11** [comment]
מצחיק רק קצת :) 
אני חושב שהסה"כ יהיה חשוב בקליטה במחסן ולא בהכרח למתנדב עצמו. 
אבל יכול להיות שאם הכל יהיה מסודר נכון (נחליף סלים בסוגי ציוד ותהיה ספירה נכונה של הציודים) אז בהחלט נשקול להחזיר את סיכום המשלוח גם למתנדב 

וכן - השיוך כעת תמיד נעשה מרשימת המשלוחים (לא "מעקב") ולכן החיבור צריך להיות שם ("האם לשייך גם את המשלוחים הרשומים לאותו מתנדב?")

**Comment by noam-honig** [comment]
סבבה - אתה רוצה לעשות את זה לבד או שאני אעשה?

**Comment by noam-honig** [comment]
בוצעו השינויים הבאים בינתיים:
1. יווצרו משלוחים שונים לפי סוג סל (מחשב, לפטופ מסך)
2. אם לא פורט כמות כל שהיא - יווצר משלוח עם סוג סל "לא פורט"
3. המשתמש שמוסיף עבור השרת יקרא WIX

כל זה יהיה באויר עוד 5 דק

**Comment by noam-honig** [comment]
הוספתי שלאחר שיוך משפחה ממסך משלוחים פעילים:
אם הכתובת היא תקינה - אז אם יש עוד משלוחים באותה הכתובת, אני מציע לשייך אותם לאותו המתנדב.
אם הכתובת לא תקינה - אז אם יש עוד משלוחים לאותה משפחה - אני מציע לשייך אותם לאותו המתנדב.

זה יהיה באויר עוד 5 דק
