### ISSUE TITLE
Add route area to volunteer object

### ISSUE THREAD

**Issue by ramigeraisy** [ramigeraisy/food-basket-delivery#5]
d. להוסיף למתנדב 2 כתובות לאיזור חלוקה. (עם הקלדה משלימה של גוגל) בהגדרת אישיות – כך שהמערכת בDISPATCH תעדיף לתת לו משפחות קרובות לכתובות אלו.

הערות לפיתוח

קביעת הכתובת הראשונה לחלוקה קוראת ב asign-family.component.ts בפונקצה AddBox – בשורות 628-640 - כרגע זה הנקודה הרחוקה ביותר מהמרכז חלוקה.

**Comment by noam-honig** [comment]
בינתיים הוספתי אחת - אח"כ נדאג לעוד - קודם כל נדאג שזה יעבוד עם האחת הזו

**Comment by noam-honig** [comment]
מעכשיו בשיוך משלוח זה מתחשב בכתובת של המתנדב.
